version: '2'
services:
  app:
   build:
    context: .
   environment:
    - "DB_PORT=3306"
    - "DB_HOST=mysql"
   ports:
    - "80:80"
   depends_on: 
    - mysql
  mysql:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"

volumes:
  dbdata:
